import {Item} from "../model/Item";

export const MOCK_ITEMS: Item[]=
  [{name: "Afghanistan", url: "http://flags.fmcdn.net/data/flags/w580/af.png", value: 25500100, thematic: "Pays", unit: "Unité"},
  {name: "Afrique du Sud", url: "http://flags.fmcdn.net/data/flags/w580/za.png", value: 52981991, thematic: "Pays", unit: "Unité"},
  {name: "Albanie", url: "http://flags.fmcdn.net/data/flags/w580/al.png", value: 2821977, thematic: "Pays", unit: "Unité"},
  {name: "Algérie", url: "http://flags.fmcdn.net/data/flags/w580/dz.png", value: 38700000, thematic: "Pays", unit: "Unité"},
  {name: "Allemagne", url: "http://flags.fmcdn.net/data/flags/w580/de.png", value: 80619000, thematic: "Pays", unit: "Unité"},
  {name: "Andorre", url: "http://flags.fmcdn.net/data/flags/w580/ad.png", value: 76098, thematic: "Pays", unit: "Unité"},
  {name: "Angola", url: "http://flags.fmcdn.net/data/flags/w580/ao.png", value: 20609294, thematic: "Pays", unit: "Unité"},
  {name: "Antigua-et-Barbuda", url: "http://flags.fmcdn.net/data/flags/w580/ag.png", value: 86295, thematic: "Pays", unit: "Unité"},
  {name: "Arabie saoudite", url: "http://flags.fmcdn.net/data/flags/w580/sa.png", value: 29994272, thematic: "Pays", unit: "Unité"},
  {name: "Argentine", url: "http://flags.fmcdn.net/data/flags/w580/ar.png", value: 41660096, thematic: "Pays", unit: "Unité"},
  {name: "Arménie", url: "http://flags.fmcdn.net/data/flags/w580/am.png", value: 3017400, thematic: "Pays", unit: "Unité"},
  {name: "Australie", url: "http://flags.fmcdn.net/data/flags/h80/au.png", value: 23414552, thematic: "Pays", unit: "Unité"},
  {name: "Autriche", url: "http://flags.fmcdn.net/data/flags/w580/at.png", value: 8504850, thematic: "Pays", unit: "Unité"},
  {name: "Azerbaïdjan", url: "http://flags.fmcdn.net/data/flags/w580/az.png", value: 9477100, thematic: "Pays", unit: "Unité"},
  {name: "Bahamas", url: "http://flags.fmcdn.net/data/flags/w580/bs.png", value: 351461, thematic: "Pays", unit: "Unité"},
  {name: "Bahreïn", url: "http://flags.fmcdn.net/data/flags/w580/bh.png", value: 1234571, thematic: "Pays", unit: "Unité"},
  {name: "Bangladesh", url: "http://flags.fmcdn.net/data/flags/w580/bd.png", value: 152518015, thematic: "Pays", unit: "Unité"},
  {name: "Barbade", url: "http://flags.fmcdn.net/data/flags/w580/bb.png", value: 285000, thematic: "Pays", unit: "Unité"},
  {name: "Belgique", url: "http://flags.fmcdn.net/data/flags/w580/be.png", value: 11132269, thematic: "Pays", unit: "Unité"},
  {name: "Belize", url: "http://flags.fmcdn.net/data/flags/w580/bz.png", value: 349728, thematic: "Pays", unit: "Unité"},
  {name: "Bénin", url: "http://flags.fmcdn.net/data/flags/w580/bj.png", value: 10323000, thematic: "Pays", unit: "Unité"},
  {name: "Bhoutan", url: "http://flags.fmcdn.net/data/flags/w580/bt.png", value: 745200, thematic: "Pays", unit: "Unité"},
  {name: "Biélorussie", url: "http://flags.fmcdn.net/data/flags/w580/by.png", value: 9468100, thematic: "Pays", unit: "Unité"},
  {name: "Birmanie", url: "http://flags.fmcdn.net/data/flags/w580/mm.png", value: 53259000, thematic: "Pays", unit: "Unité"},
  {name: "Bolivie", url: "http://flags.fmcdn.net/data/flags/w580/bo.png", value: 10027254, thematic: "Pays", unit: "Unité"},
  {name: "Bosnie-Herzégovine", url: "http://flags.fmcdn.net/data/flags/w580/ba.png", value: 3791622, thematic: "Pays", unit: "Unité"},
  {name: "Botswana", url: "http://flags.fmcdn.net/data/flags/w580/bw.png", value: 2024904, thematic: "Pays", unit: "Unité"},
  {name: "Brésil", url: "http://flags.fmcdn.net/data/flags/w580/br.png", value: 201032714, thematic: "Pays", unit: "Unité"},
  {name: "Brunei", url: "http://flags.fmcdn.net/data/flags/w580/bn.png", value: 393162, thematic: "Pays", unit: "Unité"},
  {name: "Bulgarie", url: "http://flags.fmcdn.net/data/flags/w580/bg.png", value: 7282041, thematic: "Pays", unit: "Unité"},
  {name: "Burkina Faso", url: "http://flags.fmcdn.net/data/flags/h80/bf.png", value: 17322796, thematic: "Pays", unit: "Unité"},
  {name: "Burundi", url: "http://flags.fmcdn.net/data/flags/w580/bi.png", value: 10163000, thematic: "Pays", unit: "Unité"},
  {name: "Cambodge", url: "http://flags.fmcdn.net/data/flags/w580/kh.png", value: 15135000, thematic: "Pays", unit: "Unité"},
  {name: "Cameroun", url: "http://flags.fmcdn.net/data/flags/w580/cm.png", value: 20386799, thematic: "Pays", unit: "Unité"},
  {name: "Canada", url: "http://flags.fmcdn.net/data/flags/w580/ca.png", value: 35295770, thematic: "Pays", unit: "Unité"},
  {name: "Cap-Vert", url: "http://flags.fmcdn.net/data/flags/w580/cv.png", value: 491875, thematic: "Pays", unit: "Unité"},
  {name: "Centrafrique", url: "http://flags.fmcdn.net/data/flags/w580/cf.png", value: 4616000, thematic: "Pays", unit: "Unité"},
  {name: "Chili", url: "http://flags.fmcdn.net/data/flags/w580/cl.png", value: 16341929, thematic: "Pays", unit: "Unité"},
  {name: "Chine", url: "http://flags.fmcdn.net/data/flags/w580/cn.png", value: 1363350000, thematic: "Pays", unit: "Unité"},
  {name: "Chypre", url: "http://flags.fmcdn.net/data/flags/w580/cy.png", value: 865878, thematic: "Pays", unit: "Unité"},
  {name: "Colombie", url: "http://flags.fmcdn.net/data/flags/w580/co.png", value: 47506000, thematic: "Pays", unit: "Unité"},
  {name: "Comores", url: "http://flags.fmcdn.net/data/flags/w580/km.png", value: 743798, thematic: "Pays", unit: "Unité"},
  {name: "Congo-Brazzaville / (Congo)", url: "http://flags.fmcdn.net/data/flags/w580/cg.png", value: 4448000, thematic: "Pays", unit: "Unité"},
  {name: "Congo-Kinshasa / (République démocratique du Congo)", url: "http://flags.fmcdn.net/data/flags/w580/cd.png", value: 67514000, thematic: "Pays", unit: "Unité"},
  {name: "Corée du Nord", url: "http://flags.fmcdn.net/data/flags/w580/kp.png", value: 24895000, thematic: "Pays", unit: "Unité"},
  {name: "Corée du Sud", url: "http://flags.fmcdn.net/data/flags/w580/kr.png", value: 50219669, thematic: "Pays", unit: "Unité"},
  {name: "Costa Rica", url: "http://flags.fmcdn.net/data/flags/w580/cr.png", value: 4667096, thematic: "Pays", unit: "Unité"},
  {name: "Côte d'Ivoire", url: "http://flags.fmcdn.net/data/flags/w580/ci.png", value: 23202000, thematic: "Pays", unit: "Unité"},
  {name: "Croatie", url: "http://flags.fmcdn.net/data/flags/w580/hr.png", value: 4290612, thematic: "Pays", unit: "Unité"},
  {name: "Cuba", url: "http://flags.fmcdn.net/data/flags/w580/cu.png", value: 11167325, thematic: "Pays", unit: "Unité"},
  {name: "Danemark", url: "http://flags.fmcdn.net/data/flags/w580/dk.png", value: 5627235, thematic: "Pays", unit: "Unité"},
  {name: "Djibouti", url: "http://flags.fmcdn.net/data/flags/w580/dj.png", value: 873000, thematic: "Pays", unit: "Unité"},
  {name: "Dominique", url: "http://flags.fmcdn.net/data/flags/w580/dm.png", value: 71293, thematic: "Pays", unit: "Unité"},
  {name: "Égypte", url: "http://flags.fmcdn.net/data/flags/h80/eg.png", value: 86127000, thematic: "Pays", unit: "Unité"},
  {name: "Émirats arabes unis", url: "http://flags.fmcdn.net/data/flags/w580/ae.png", value: 8264070, thematic: "Pays", unit: "Unité"},
  {name: "Équateur", url: "http://flags.fmcdn.net/data/flags/w580/ec.png", value: 15699200, thematic: "Pays", unit: "Unité"},
  {name: "Érythrée", url: "http://flags.fmcdn.net/data/flags/w580/er.png", value: 6333000, thematic: "Pays", unit: "Unité"},
  {name: "Espagne", url: "http://flags.fmcdn.net/data/flags/w580/es.png", value: 46609700, thematic: "Pays", unit: "Unité"},
  {name: "Estonie", url: "http://flags.fmcdn.net/data/flags/w580/ee.png", value: 1311870, thematic: "Pays", unit: "Unité"},
  {name: "États-Unis", url: "http://flags.fmcdn.net/data/flags/w580/us.png", value: 317706000, thematic: "Pays", unit: "Unité"},
  {name: "Éthiopie", url: "http://flags.fmcdn.net/data/flags/w580/et.png", value: 86613986, thematic: "Pays", unit: "Unité"},
  {name: "Fidji", url: "http://flags.fmcdn.net/data/flags/w580/fj.png", value: 858038, thematic: "Pays", unit: "Unité"},
  {name: "Finlande", url: "http://flags.fmcdn.net/data/flags/w580/fi.png", value: 5452821, thematic: "Pays", unit: "Unité"},
  {name: "France", url: "http://flags.fmcdn.net/data/flags/w580/fr.png", value: 65844000, thematic: "Pays", unit: "Unité"},
  {name: "Gabon", url: "http://flags.fmcdn.net/data/flags/w580/ga.png", value: 1672000, thematic: "Pays", unit: "Unité"},
  {name: "Gambie", url: "http://flags.fmcdn.net/data/flags/w580/gm.png", value: 1849000, thematic: "Pays", unit: "Unité"},
  {name: "Géorgie", url: "http://flags.fmcdn.net/data/flags/w580/ge.png", value: 4483800, thematic: "Pays", unit: "Unité"},
  {name: "Ghana", url: "http://flags.fmcdn.net/data/flags/w580/gh.png", value: 24658823, thematic: "Pays", unit: "Unité"},
  {name: "Grèce", url: "http://flags.fmcdn.net/data/flags/w580/gr.png", value: 10815197, thematic: "Pays", unit: "Unité"},
  {name: "Grenade", url: "http://flags.fmcdn.net/data/flags/w580/gd.png", value: 103328, thematic: "Pays", unit: "Unité"},
  {name: "Guatemala", url: "http://flags.fmcdn.net/data/flags/w580/gt.png", value: 15806675, thematic: "Pays", unit: "Unité"},
  {name: "Guinée", url: "http://flags.fmcdn.net/data/flags/w580/gn.png", value: 10824200, thematic: "Pays", unit: "Unité"},
  {name: "Guinée équatoriale", url: "http://flags.fmcdn.net/data/flags/w580/gq.png", value: 736296, thematic: "Pays", unit: "Unité"},
  {name: "Guinée-Bissau", url: "http://flags.fmcdn.net/data/flags/w580/gw.png", value: 1704000, thematic: "Pays", unit: "Unité"},
  {name: "Guyana", url: "http://flags.fmcdn.net/data/flags/w580/gy.png", value: 784894, thematic: "Pays", unit: "Unité"},
  {name: "Haïti", url: "http://flags.fmcdn.net/data/flags/w580/ht.png", value: 10413211, thematic: "Pays", unit: "Unité"},
  {name: "Honduras", url: "http://flags.fmcdn.net/data/flags/w580/hn.png", value: 8555072, thematic: "Pays", unit: "Unité"},
  {name: "Hongrie", url: "http://flags.fmcdn.net/data/flags/w580/hu.png", value: 9906000, thematic: "Pays", unit: "Unité"},
  {name: "Îles Cook", url: "http://flags.fmcdn.net/data/flags/w580/ck.png", value: 14974, thematic: "Pays", unit: "Unité"},
  {name: "Îles Salomon", url: "http://flags.fmcdn.net/data/flags/w580/sb.png", value: 581344, thematic: "Pays", unit: "Unité"},
  {name: "Inde", url: "http://flags.fmcdn.net/data/flags/w580/in.png", value: 1241610000, thematic: "Pays", unit: "Unité"},
  {name: "Indonésie", url: "http://flags.fmcdn.net/data/flags/w580/id.png", value: 249866000, thematic: "Pays", unit: "Unité"},
  {name: "Irak", url: "http://flags.fmcdn.net/data/flags/w580/iq.png", value: 34035000, thematic: "Pays", unit: "Unité"},
  {name: "Iran", url: "http://flags.fmcdn.net/data/flags/w580/ir.png", value: 77288000, thematic: "Pays", unit: "Unité"},
  {name: "Irlande", url: "http://flags.fmcdn.net/data/flags/w580/ie.png", value: 4593100, thematic: "Pays", unit: "Unité"},
  {name: "Islande", url: "http://flags.fmcdn.net/data/flags/w580/is.png", value: 325671, thematic: "Pays", unit: "Unité"},
  {name: "Israël", url: "http://flags.fmcdn.net/data/flags/w580/il.png", value: 8146300, thematic: "Pays", unit: "Unité"},
  {name: "Italie", url: "http://flags.fmcdn.net/data/flags/w580/it.png", value: 59943933, thematic: "Pays", unit: "Unité"},
  {name: "Jamaïque", url: "http://flags.fmcdn.net/data/flags/w580/jm.png", value: 2711476, thematic: "Pays", unit: "Unité"},
  {name: "Japon", url: "http://flags.fmcdn.net/data/flags/w580/jp.png", value: 127180000, thematic: "Pays", unit: "Unité"},
  {name: "Jordanie", url: "http://flags.fmcdn.net/data/flags/w580/jo.png", value: 6558900, thematic: "Pays", unit: "Unité"},
  {name: "Kazakhstan", url: "http://flags.fmcdn.net/data/flags/w580/kz.png", value: 17186000, thematic: "Pays", unit: "Unité"},
  {name: "Kenya", url: "http://flags.fmcdn.net/data/flags/w580/ke.png", value: 44354000, thematic: "Pays", unit: "Unité"},
  {name: "Kirghizistan", url: "http://flags.fmcdn.net/data/flags/w580/kg.png", value: 5663133, thematic: "Pays", unit: "Unité"},
  {name: "Kiribati", url: "http://flags.fmcdn.net/data/flags/w580/ki.png", value: 106461, thematic: "Pays", unit: "Unité"},
  {name: "Kosovo", url: "http://flags.fmcdn.net/data/flags/w580/ks.png", value: 1815606, thematic: "Pays", unit: "Unité"},
  {name: "Koweït", url: "http://flags.fmcdn.net/data/flags/w580/kw.png", value: 3065850, thematic: "Pays", unit: "Unité"},
  {name: "Laos", url: "http://flags.fmcdn.net/data/flags/w580/la.png", value: 6580800, thematic: "Pays", unit: "Unité"},
  {name: "Lesotho", url: "http://flags.fmcdn.net/data/flags/w580/ls.png", value: 2074000, thematic: "Pays", unit: "Unité"},
  {name: "Lettonie", url: "http://flags.fmcdn.net/data/flags/w580/lv.png", value: 2003900, thematic: "Pays", unit: "Unité"},
  {name: "Liban", url: "http://flags.fmcdn.net/data/flags/w580/lb.png", value: 4822000, thematic: "Pays", unit: "Unité"},
  {name: "Libéria", url: "http://flags.fmcdn.net/data/flags/w580/lr.png", value: 4294000, thematic: "Pays", unit: "Unité"},
  {name: "Libye", url: "http://flags.fmcdn.net/data/flags/w580/ly.png", value: 6202000, thematic: "Pays", unit: "Unité"},
  {name: "Liechtenstein", url: "http://flags.fmcdn.net/data/flags/w580/li.png", value: 37132, thematic: "Pays", unit: "Unité"},
  {name: "Lituanie", url: "http://flags.fmcdn.net/data/flags/w580/lt.png", value: 2941953, thematic: "Pays", unit: "Unité"},
  {name: "Luxembourg", url: "http://flags.fmcdn.net/data/flags/w580/lu.png", value: 537000, thematic: "Pays", unit: "Unité"},
  {name: "Macédoine", url: "http://flags.fmcdn.net/data/flags/w580/mk.png", value: 2062294, thematic: "Pays", unit: "Unité"},
  {name: "Madagascar", url: "http://flags.fmcdn.net/data/flags/w580/mg.png", value: 21263403, thematic: "Pays", unit: "Unité"},
  {name: "Malaisie", url: "http://flags.fmcdn.net/data/flags/w580/my.png", value: 30041000, thematic: "Pays", unit: "Unité"},
  {name: "Malawi", url: "http://flags.fmcdn.net/data/flags/w580/mw.png", value: 16363000, thematic: "Pays", unit: "Unité"},
  {name: "Maldives", url: "http://flags.fmcdn.net/data/flags/w580/mv.png", value: 317280, thematic: "Pays", unit: "Unité"},
  {name: "Mali", url: "http://flags.fmcdn.net/data/flags/w580/ml.png", value: 15302000, thematic: "Pays", unit: "Unité"},
  {name: "Malte", url: "http://flags.fmcdn.net/data/flags/w580/mt.png", value: 416055, thematic: "Pays", unit: "Unité"},
  {name: "Maroc", url: "http://flags.fmcdn.net/data/flags/w580/ma.png", value: 33202300, thematic: "Pays", unit: "Unité"},
  {name: "Marshall", url: "http://flags.fmcdn.net/data/flags/w580/mh.png", value: 56086, thematic: "Pays", unit: "Unité"},
  {name: "Maurice", url: "http://flags.fmcdn.net/data/flags/w580/mu.png", value: 1257900, thematic: "Pays", unit: "Unité"},
  {name: "Mauritanie", url: "http://flags.fmcdn.net/data/flags/w580/mr.png", value: 3461041, thematic: "Pays", unit: "Unité"},
  {name: "Mexique", url: "http://flags.fmcdn.net/data/flags/w580/mx.png", value: 119713203, thematic: "Pays", unit: "Unité"},
  {name: "Micronésie", url: "http://flags.fmcdn.net/data/flags/w580/fm.png", value: 101351, thematic: "Pays", unit: "Unité"},
  {name: "Moldavie", url: "http://flags.fmcdn.net/data/flags/w580/md.png", value: 3559500, thematic: "Pays", unit: "Unité"},
  {name: "Monaco", url: "http://flags.fmcdn.net/data/flags/w580/mc.png", value: 36136, thematic: "Pays", unit: "Unité"},
  {name: "Mongolie", url: "http://flags.fmcdn.net/data/flags/w580/mn.png", value: 2931300, thematic: "Pays", unit: "Unité"},
  {name: "Monténégro", url: "http://flags.fmcdn.net/data/flags/w580/me.png", value: 620029, thematic: "Pays", unit: "Unité"},
  {name: "Mozambique", url: "http://flags.fmcdn.net/data/flags/w580/mz.png", value: 23700715, thematic: "Pays", unit: "Unité"},
  {name: "Namibie", url: "http://flags.fmcdn.net/data/flags/w580/na.png", value: 2113077, thematic: "Pays", unit: "Unité"},
  {name: "Nauru", url: "http://flags.fmcdn.net/data/flags/w580/nr.png", value: 9945, thematic: "Pays", unit: "Unité"},
  {name: "Népal", url: "http://flags.fmcdn.net/data/flags/w580/np.png", value: 26494504, thematic: "Pays", unit: "Unité"},
  {name: "Nicaragua", url: "http://flags.fmcdn.net/data/flags/w580/ni.png", value: 6071045, thematic: "Pays", unit: "Unité"},
  {name: "Niger", url: "http://flags.fmcdn.net/data/flags/w580/ne.png", value: 17129076, thematic: "Pays", unit: "Unité"},
  {name: "Nigeria", url: "http://flags.fmcdn.net/data/flags/w580/ng.png", value: 173615000, thematic: "Pays", unit: "Unité"},
  {name: "Niue", url: "http://flags.fmcdn.net/data/flags/w580/nu.png", value: 1611, thematic: "Pays", unit: "Unité"},
  {name: "Norvège", url: "http://flags.fmcdn.net/data/flags/w580/no.png", value: 5109056, thematic: "Pays", unit: "Unité"},
  {name: "Nouvelle-Zélande", url: "http://flags.fmcdn.net/data/flags/w580/nz.png", value: 4518330, thematic: "Pays", unit: "Unité"},
  {name: "Oman", url: "http://flags.fmcdn.net/data/flags/w580/om.png", value: 3957000, thematic: "Pays", unit: "Unité"},
  {name: "Ouganda", url: "http://flags.fmcdn.net/data/flags/w580/ug.png", value: 35357000, thematic: "Pays", unit: "Unité"},
  {name: "Ouzbékistan", url: "http://flags.fmcdn.net/data/flags/w580/uz.png", value: 30183400, thematic: "Pays", unit: "Unité"},
  {name: "Pakistan", url: "http://flags.fmcdn.net/data/flags/w580/pk.png", value: 185914000, thematic: "Pays", unit: "Unité"},
  {name: "Palaos", url: "http://flags.fmcdn.net/data/flags/w580/pw.png", value: 20901, thematic: "Pays", unit: "Unité"},
  {name: "Panamá", url: "http://flags.fmcdn.net/data/flags/w580/pa.png", value: 3405813, thematic: "Pays", unit: "Unité"},
  {name: "Papouasie-Nouvelle-Guinée", url: "http://flags.fmcdn.net/data/flags/w580/pg.png", value: 7398500, thematic: "Pays", unit: "Unité"},
  {name: "Paraguay", url: "http://flags.fmcdn.net/data/flags/w580/py.png", value: 6783374, thematic: "Pays", unit: "Unité"},
  {name: "Pays-Bas", url: "http://flags.fmcdn.net/data/flags/w580/nl.png", value: 16842200, thematic: "Pays", unit: "Unité"},
  {name: "Pérou", url: "http://flags.fmcdn.net/data/flags/w580/pe.png", value: 30475144, thematic: "Pays", unit: "Unité"},
  {name: "Philippines", url: "http://flags.fmcdn.net/data/flags/w580/ph.png", value: 99275100, thematic: "Pays", unit: "Unité"},
  {name: "Pologne", url: "http://flags.fmcdn.net/data/flags/w580/pl.png", value: 38502396, thematic: "Pays", unit: "Unité"},
  {name: "Portugal", url: "http://flags.fmcdn.net/data/flags/w580/pt.png", value: 10487289, thematic: "Pays", unit: "Unité"},
  {name: "Qatar", url: "http://flags.fmcdn.net/data/flags/w580/qa.png", value: 2045239, thematic: "Pays", unit: "Unité"},
  {name: "République dominicaine", url: "http://flags.fmcdn.net/data/flags/w580/do.png", value: 9445281, thematic: "Pays", unit: "Unité"},
  {name: "République tchèque", url: "http://flags.fmcdn.net/data/flags/w580/cz.png", value: 10513800, thematic: "Pays", unit: "Unité"},
  {name: "Roumanie", url: "http://flags.fmcdn.net/data/flags/w580/ro.png", value: 20121641, thematic: "Pays", unit: "Unité"},
  {name: "Royaume-Uni", url: "http://flags.fmcdn.net/data/flags/w580/gb.png", value: 63705000, thematic: "Pays", unit: "Unité"},
  {name: "Russie", url: "http://flags.fmcdn.net/data/flags/w580/ru.png", value: 143700000, thematic: "Pays", unit: "Unité"},
  {name: "Rwanda", url: "http://flags.fmcdn.net/data/flags/w580/rw.png", value: 10537222, thematic: "Pays", unit: "Unité"},
  {name: "Sahara occidental", url: "http://flags.fmcdn.net/data/flags/w580/eh.png", value: 567000, thematic: "Pays", unit: "Unité"},
  {name: "Saint-Christophe-et-Niévès", url: "http://flags.fmcdn.net/data/flags/w580/kn.png", value: 54000, thematic: "Pays", unit: "Unité"},
  {name: "Saint-Marin", url: "http://flags.fmcdn.net/data/flags/w580/sm.png", value: 33540, thematic: "Pays", unit: "Unité"},
  {name: "Saint-Vincent-et-les Grenadines", url: "http://flags.fmcdn.net/data/flags/w580/vc.png", value: 109000, thematic: "Pays", unit: "Unité"},
  {name: "Sainte-Lucie", url: "http://flags.fmcdn.net/data/flags/w580/lc.png", value: 180000, thematic: "Pays", unit: "Unité"},
  {name: "Salvador", url: "http://flags.fmcdn.net/data/flags/w580/sv.png", value: 6340000, thematic: "Pays", unit: "Unité"},
  {name: "Samoa", url: "http://flags.fmcdn.net/data/flags/w580/ws.png", value: 187820, thematic: "Pays", unit: "Unité"},
  {name: "São Tomé-et-Principe", url: "http://flags.fmcdn.net/data/flags/w580/st.png", value: 187356, thematic: "Pays", unit: "Unité"},
  {name: "Sénégal", url: "http://flags.fmcdn.net/data/flags/w580/sn.png", value: 13567338, thematic: "Pays", unit: "Unité"},
  {name: "Serbie", url: "http://flags.fmcdn.net/data/flags/w580/rs.png", value: 7181505, thematic: "Pays", unit: "Unité"},
  {name: "Seychelles", url: "http://flags.fmcdn.net/data/flags/w580/sc.png", value: 90945, thematic: "Pays", unit: "Unité"},
  {name: "Sierra Leone", url: "http://flags.fmcdn.net/data/flags/w580/sl.png", value: 6190280, thematic: "Pays", unit: "Unité"},
  {name: "Singapour", url: "http://flags.fmcdn.net/data/flags/w580/sg.png", value: 5399200, thematic: "Pays", unit: "Unité"},
  {name: "Slovaquie", url: "http://flags.fmcdn.net/data/flags/w580/sk.png", value: 5415949, thematic: "Pays", unit: "Unité"},
  {name: "Slovénie", url: "http://flags.fmcdn.net/data/flags/w580/si.png", value: 2061963, thematic: "Pays", unit: "Unité"},
  {name: "Somalie", url: "http://flags.fmcdn.net/data/flags/w580/so.png", value: 10496000, thematic: "Pays", unit: "Unité"},
  {name: "Soudan", url: "http://flags.fmcdn.net/data/flags/w580/sd.png", value: 37964000, thematic: "Pays", unit: "Unité"},
  {name: "Soudan du Sud", url: "http://flags.fmcdn.net/data/flags/w580/ss.png", value: 10625176, thematic: "Pays", unit: "Unité"},
  {name: "Sri Lanka", url: "http://flags.fmcdn.net/data/flags/w580/lk.png", value: 20277597, thematic: "Pays", unit: "Unité"},
  {name: "Suède", url: "http://flags.fmcdn.net/data/flags/w580/se.png", value: 9651531, thematic: "Pays", unit: "Unité"},
  {name: "Suisse", url: "http://flags.fmcdn.net/data/flags/w580/ch.png", value: 8112200, thematic: "Pays", unit: "Unité"},
  {name: "Suriname", url: "http://flags.fmcdn.net/data/flags/w580/sr.png", value: 534189, thematic: "Pays", unit: "Unité"},
  {name: "Swaziland", url: "http://flags.fmcdn.net/data/flags/w580/sz.png", value: 1250000, thematic: "Pays", unit: "Unité"},
  {name: "Syrie", url: "http://flags.fmcdn.net/data/flags/w580/sy.png", value: 21898000, thematic: "Pays", unit: "Unité"},
  {name: "Tadjikistan", url: "http://flags.fmcdn.net/data/flags/w580/tj.png", value: 8160000, thematic: "Pays", unit: "Unité"},
  {name: "Taiwan / (République de Chine)", url: "http://flags.fmcdn.net/data/flags/w580/tw.png", value: 23379129, thematic: "Pays", unit: "Unité"},
  {name: "Tanzanie", url: "http://flags.fmcdn.net/data/flags/w580/tz.png", value: 44928923, thematic: "Pays", unit: "Unité"},
  {name: "Tchad", url: "http://flags.fmcdn.net/data/flags/w580/td.png", value: 12825000, thematic: "Pays", unit: "Unité"},
  {name: "Thaïlande", url: "http://flags.fmcdn.net/data/flags/w580/th.png", value: 65926261, thematic: "Pays", unit: "Unité"},
  {name: "Timor oriental", url: "http://flags.fmcdn.net/data/flags/w580/tl.png", value: 1066409, thematic: "Pays", unit: "Unité"},
  {name: "Togo", url: "http://flags.fmcdn.net/data/flags/w580/tg.png", value: 6191155, thematic: "Pays", unit: "Unité"},
  {name: "Tonga", url: "http://flags.fmcdn.net/data/flags/w580/to.png", value: 103036, thematic: "Pays", unit: "Unité"},
  {name: "Trinité-et-Tobago", url: "http://flags.fmcdn.net/data/flags/w580/tt.png", value: 1328019, thematic: "Pays", unit: "Unité"},
  {name: "Tunisie", url: "http://flags.fmcdn.net/data/flags/w580/tn.png", value: 10886500, thematic: "Pays", unit: "Unité"},
  {name: "Turkménistan", url: "http://flags.fmcdn.net/data/flags/w580/tm.png", value: 5240000, thematic: "Pays", unit: "Unité"},
  {name: "Turquie", url: "http://flags.fmcdn.net/data/flags/w580/tr.png", value: 76667864, thematic: "Pays", unit: "Unité"},
  {name: "Tuvalu", url: "http://flags.fmcdn.net/data/flags/w580/tv.png", value: 11323, thematic: "Pays", unit: "Unité"},
  {name: "Ukraine", url: "http://flags.fmcdn.net/data/flags/w580/ua.png", value: 45426200, thematic: "Pays", unit: "Unité"},
  {name: "Uruguay", url: "http://flags.fmcdn.net/data/flags/w580/uy.png", value: 3286314, thematic: "Pays", unit: "Unité"},
  {name: "Vanuatu", url: "http://flags.fmcdn.net/data/flags/w580/vu.png", value: 264652, thematic: "Pays", unit: "Unité"},
  {name: "Vatican / (Saint-Siège)", url: "http://flags.fmcdn.net/data/flags/w580/va.png", value: 839, thematic: "Pays", unit: "Unité"},
  {name: "Venezuela", url: "http://flags.fmcdn.net/data/flags/w580/ve.png", value: 28946101, thematic: "Pays", unit: "Unité"},
  {name: "Viêt Nam", url: "http://flags.fmcdn.net/data/flags/w580/vn.png", value: 89708900, thematic: "Pays", unit: "Unité"},
  {name: "Yémen", url: "http://flags.fmcdn.net/data/flags/w580/ye.png", value: 25235000, thematic: "Pays", unit: "Unité"},
  {name: "Zambie", url: "http://flags.fmcdn.net/data/flags/w580/zm.png", value: 14580290, thematic: "Pays", unit: "Unité"},
  {name: "Zimbabwe", url: "http://flags.fmcdn.net/data/flags/w580/zw.png", value: 12973808, thematic: "Pays", unit: "Unité"}]
